steps:
  # Install
  - name: "gcr.io/cloud-builders/npm"
    args: ["ci"]
    dir: "nodejs"
  # Deploy
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
    dir: "nodejs"
timeout: "600s"
